# Generated by Django 6.0 on 2025-12-18 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker'), ('DEF', 'Defense/Special Teams')], max_length=3)),
                ('nfl_team', models.CharField(choices=[('ARI', 'Arizona Cardinals'), ('ATL', 'Atlanta Falcons'), ('BAL', 'Baltimore Ravens'), ('BUF', 'Buffalo Bills'), ('CAR', 'Carolina Panthers'), ('CHI', 'Chicago Bears'), ('CIN', 'Cincinnati Bengals'), ('CLE', 'Cleveland Browns'), ('DAL', 'Dallas Cowboys'), ('DEN', 'Denver Broncos'), ('DET', 'Detroit Lions'), ('GB', 'Green Bay Packers'), ('HOU', 'Houston Texans'), ('IND', 'Indianapolis Colts'), ('JAX', 'Jacksonville Jaguars'), ('KC', 'Kansas City Chiefs'), ('LAC', 'Los Angeles Chargers'), ('LAR', 'Los Angeles Rams'), ('LV', 'Las Vegas Raiders'), ('MIA', 'Miami Dolphins'), ('MIN', 'Minnesota Vikings'), ('NE', 'New England Patriots'), ('NO', 'New Orleans Saints'), ('NYG', 'New York Giants'), ('NYJ', 'New York Jets'), ('PHI', 'Philadelphia Eagles'), ('PIT', 'Pittsburgh Steelers'), ('SEA', 'Seattle Seahawks'), ('SF', 'San Francisco 49ers'), ('TB', 'Tampa Bay Buccaneers'), ('TEN', 'Tennessee Titans'), ('WAS', 'Washington Commanders')], max_length=3)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_injured', models.BooleanField(default=False)),
                ('injury_status', models.CharField(blank=True, max_length=50, null=True)),
                ('bye_week', models.PositiveIntegerField(blank=True, null=True)),
                ('points_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league_type', models.CharField(choices=[('standard', 'Standard'), ('ppr', 'PPR'), ('half_ppr', 'Half PPR'), ('dynasty', 'Dynasty'), ('keeper', 'Keeper')], default='standard', max_length=20)),
                ('scoring_type', models.CharField(choices=[('head_to_head', 'Head to Head'), ('points', 'Total Points'), ('roto', 'Rotisserie')], default='head_to_head', max_length=20)),
                ('max_teams', models.PositiveIntegerField(default=12)),
                ('is_public', models.BooleanField(default=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('draft_date', models.DateTimeField(blank=True, null=True)),
                ('season_year', models.PositiveIntegerField(default=2024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioned_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('ties', models.PositiveIntegerField(default=0)),
                ('points_for', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points_against', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_teams', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.league')),
            ],
            options={
                'unique_together': {('owner', 'league')},
            },
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('home_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('away_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchups', to='leagues.fantasyteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchups', to='leagues.fantasyteam')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='leagues.league')),
            ],
            options={
                'unique_together': {('league', 'week', 'home_team', 'away_team')},
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_position', models.CharField(choices=[('QB', 'Quarterback'), ('RB1', 'Running Back 1'), ('RB2', 'Running Back 2'), ('WR1', 'Wide Receiver 1'), ('WR2', 'Wide Receiver 2'), ('TE', 'Tight End'), ('FLEX', 'Flex'), ('K', 'Kicker'), ('DEF', 'Defense'), ('BN1', 'Bench 1'), ('BN2', 'Bench 2'), ('BN3', 'Bench 3'), ('BN4', 'Bench 4'), ('BN5', 'Bench 5'), ('IR', 'Injured Reserve')], max_length=4)),
                ('is_starter', models.BooleanField(default=False)),
                ('acquired_date', models.DateTimeField(auto_now_add=True)),
                ('fantasy_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='leagues.fantasyteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_assignments', to='leagues.nflplayer')),
            ],
            options={
                'unique_together': {('fantasy_team', 'player')},
            },
        ),
    ]
